# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mytime.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QApplication,QMainWindow
import sys,os
import time,json


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowTitle('MyTime')
        MainWindow.resize(800, 600)

        self.on = False # 开关标志
        self.t1 = 0 # 前一次计时时间

        localtime = time.localtime(time.time())#本地时间
        self.date = '%s-%s-%s'%(localtime.tm_year,localtime.tm_mon,localtime.tm_mday)#转换成日期

        # 读取记录
        self.history = {}
        self.read_history()
        if self.date not in self.history.keys():
            self.history[self.date] = 0

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 150, 421, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.label_0 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_0.setObjectName("label_0")
        self.verticalLayout.addWidget(self.label_0)

        self.label_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_1.setObjectName("label")
        self.verticalLayout.addWidget(self.label_1)

        self.button1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button1.setObjectName("pushButton")
        self.button1.setText('开始')
        self.button1.clicked.connect(self.onButtonClick)
        self.verticalLayout.addWidget(self.button1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        totalmin = self.history[self.date]//60
        totalhour = totalmin//60
        self.label_0.setText("今天是%s，已学习%dh %dmin %ds"%(self.date,totalhour,totalmin%60,self.history[self.date]%60))
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def onButtonClick(self): 
        if not self.on:
            self.button1.setText('结束')
            self.t1 = time.time()
            self.label_1.setText('开始计时，加油！')
            self.on = True
        else:
            self.button1.setText('开始')
            self.history[self.date] += time.time()-self.t1
            self.label_1.setText('已停止计时，快来！')
            totalmin = self.history[self.date]//60
            totalhour = totalmin//60
            self.label_0.setText("今天是%s，已学习%dh %dmin %ds"%(self.date,totalhour,totalmin%60,self.history[self.date]%60))
            self.on = False
            with open('data.json', 'w') as f:
                json.dump(self.history, f)
    
    def read_history(self):
        if os.path.exists('data.json'):
            with open('data.json', 'r') as f:
                self.history = json.load(f)

if __name__ == "__main__":  
    app = QApplication(sys.argv)  
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())